### ISSUE TITLE
Library can't parse multiline values properly

### ISSUE THREAD

**Issue by x1unix** [joho/godotenv#117] opened 2020-09-09 13:24 UTC
Library doesn't parse multi-line variable values properly.

**Input**:

```bash
URLS="foo
bar"
```

**Expected:**

```go
map[string]string{
  "URLS": "foo\nbar",
}
```

**Got:**

```go
map[string]string{
  "URLS": "foo",
  "bar",
}
```

**Comment by x1unix** [comment] 2020-09-09 13:24
@joho I'm already working on fix, but this requires a major rewrite of parser implementation

**Comment by x1unix** [comment] 2020-09-10 04:31
@joho added PR with issue fix - https://github.com/joho/godotenv/pull/118.

Please take a look

**Comment by joho** [comment] 2020-11-08 01:09
Duplicate of #64

**Closed by joho** 2020-11-08 01:09 UTC
