### ISSUE TITLE
attach binary file in the release?

### ISSUE THREAD

**Issue by c9s** [joho/godotenv#130] opened 2020-12-31 06:13 UTC
Hi!

really like the godotenv package because it's tiny and lightweight, however when we deploy application to production, we don't want to install the go compile tools on the machine, we should like to use the binary directly.

could you attach the compiled binary to the release, so that we can download it just through curl command?  thank you~

**Comment by coolaj86** [comment] 2021-03-08 18:15
I made the binary available here: https://webinstall.dev/dotenv/
And here: https://github.com/therootcompany/dotenv/releases

Same library, just extended the CLI to include version info.

**Comment by joho** [comment] 2021-03-08 22:11
Duplicate of #116, will push a release with the binaries attached soon

**Closed by joho** 2021-03-08 22:11 UTC
