### ISSUE TITLE
.dotenv does not work in go test

### ISSUE THREAD

**Issue by eugbyte** [joho/godotenv#154] opened 2021-08-26 15:22 UTC
```
err := godotenv.Load()
	if err != nil {
		log.Fatalf("Error loading .env file: %v", err)
	}
```

No error is produced when running in development. However, when testing, e.g. go test, I get the error
```
Error loading .env file: open .env: The system cannot find the file specified.
```

Looks like during go test, the root directory is no longer respected

**Comment by joho** [comment] 2021-09-24 11:22
duplicate of #126

**Closed by joho** 2021-09-24 11:22 UTC
